
namespace Vetsys.API.Modules.Customers.DTOs
{
    public class CustomerCreateDTO
    {
        public required Guid Id { get; set; } // This property can be removed if the ID is generated by the backend
        public required string Name { get; set; } 
        public required string LastName { get; set; } 
        public required string Email { get; set; }

    }
}
