
namespace Vetsys.API.Modules.Customers.DTOs
{
    public record CustomerCreateDTO
    {
        public required Guid Id { get; init; } // This property can be removed if the ID is generated by the backend
        public required string Name { get; init; } 
        public required string LastName { get; init; } 
        public required string Email { get; init; }

    }
}
