
namespace Vetsys.API.Modules.Customers.DTOs
{
    public class CustomerCreateDTO
    {
        public Guid Id { get; set; } // This property can be removed if the ID is generated by the backend
        public string Name { get; set; } = string.Empty;
        public string LastName { get; set; } = string.Empty;
        public string? Email { get; set; }

    }
}
